{"description": "If `pkcs12.serialize_key_and_certificates` is called with both:\n\n1. A certificate whose public key did not match the provided private key\n2. An `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`\n\nThen a NULL pointer dereference would occur, crashing the Python process.\n\nThis has been resolved, and now a `ValueError` is properly raised.\n\nPatched in https://github.com/pyca/cryptography/pull/10423", "methods": ["NULL pointer dereference via pkcs12.serialize_key_and_certificates with mismatched certificate and private key.", "NULL pointer dereference via pkcs12.serialize_key_and_certificates with hmac_hash override.", "Use of a vulnerability in the cryptography library.", "Use of a library with a known vulnerability (cryptography)."]}