{"description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.", "methods": ["Establishes and immediately closes a TCP connection to cause a denial of service.", "Exploits a race condition in the FTPHandler class in ftpserver.py.", "Causes the accept function to have an unexpected value of None for the address.", "Causes an ECONNABORTED, EAGAIN, or EWOULDBLOCK error."]}