{"description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1 (OpenCV-Python before 3.4.7.28 and 4.x before 4.1.1.26). There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.", "methods": ["Used out-of-bounds read in OpenCV's HaarEvaluator::OptFeature::calc function.", "Used out-of-bounds write in OpenCV's HaarEvaluator::OptFeature::calc function.", "Caused denial of service."]}