{"description": "### Impact \nThe [implementation of `*Bincount` operations](https://github.com/tensorflow/tensorflow/blob/5100e359aef5c8021f2e71c7b986420b85ce7b3d/tensorflow/core/kernels/bincount_op.cc) allows malicious users to cause denial of service by passing in arguments which would trigger a `CHECK`-fail:\n\n```python\nimport tensorflow as tf\n\ntf.raw_ops.DenseBincount(\n  input=[[0], [1], [2]],\n  size=[1],\n  weights=[3,2,1],\n  binary_output=False)\n```\n\nThere are several conditions that the input arguments must satisfy. Some are not caught during shape inference and others are not caught during kernel implementation. This results in `CHECK` failures later when the output tensors get allocated.\n\n### Patches\nWe have patched the issue in GitHub commit [7019ce4f68925fd01cdafde26f8d8c938f47e6f9](https://github.com/tensorflow/tensorflow/commit/7019ce4f68925fd01cdafde26f8d8c938f47e6f9).\n\nThe fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by Faysal Hossain Shezan from University of Virginia.", "methods": ["Assertion failure based denial of service in Tensorflow.", "Triggered by passing in arguments that would trigger a CHECK-fail.", "Not caught during shape inference.", "Not caught during kernel implementation.", "Results in CHECK failures when output tensors get allocated.", "Patched in GitHub commit 7019ce4f68925fd01cdafde26f8d8c938f47e6f9.", "Fix included in TensorFlow 2.8.0.", "Cherrypicked in TensorFlow 2.7.1, 2.6.3, and 2.5.3."]}