{"description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.", "methods": ["Attempted Denial of Service (DoS) via large input with a very large number of brackets."]}